### ISSUE TITLE
Не создает папку "Garrys_mod_ES" и нет логов о .lua

### ISSUE THREAD

**Issue by Gudov** [EinsatzGruppen/EinsatzScan#3]
При инжекте .dll, создается консольное окно и появляется надпись "[EinsatzScan] Injected successful.".
Во время захода на сервер ничего не происходит. 
Через несколько дней приложу дамп, если надо.

**Comment by Heyter** [comment]
Может потому что, гарри выпустил обновление, которое закрывает некоторые дыры гмода?
Как и скриптхук, они больше не рабочие. Не знаю, будет ли обнова.

**Comment by SchwarzKruppzo** [comment]
Updated for a newer version of Garry's Mod.
